service: slack-bot

provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: ap-northeast-1
  deploymentBucket: ${ssm:sls_deployment_bucket}
  logRetentionInDays: 7
  timeout: 60
  memorySize: 256
  environment:
    TZ: Asia/Tokyo
    SLACK_TOKEN: ${ssm:slack_bot_token~true}
    SLACK_CHANNEL: ${ssm:slack_bot_channel}

functions:
  postNewChannels:
    handler: src/post_new_channels.lambda_handler
    events:
      - schedule:
          rate: cron(0 3 * * ? *)

package:
  exclude:
    - .venv/**

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin

custom:
  pythonRequirements:
    usePipenv: true

  prune:
    automatic: true
    number: 3
