service: ecwms-mail-api

provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: ap-northeast-1
  deploymentBucket: sls-deployment-#{AWS::AccountId}
  logRetentionInDays: 7
  timeout: 60
  memorySize: 256
  environment:
    TZ: Asia/Tokyo
    SLACK_TOKEN: ${ssm:slack_bot_token~true}
    SLACK_CHANNEL: ${ssm:slack_bot_channel}

functions:
  postNewChannels:
    handler: src/post_new_channels.lambda_handler
    events:
      - schedule:
          rate: cron(0 3 * * ? *)

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

custom:
  pythonRequirements:
    usePipenv: true
