name: Check
on: pull_request

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SLS_DEPLOYMENT_BUCKET: ${{ secrets.SLS_DEPLOYMENT_BUCKET }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install Npm
        run: npm install

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: Install dependencies
        run: |
          pip install --upgrade pip pipenv
          pipenv install --ignore-pipfile --dev
        env:
          PIPENV_NOSPIN: 1

      - name: Lint check
        run: pipenv run lint

      - name: Type check
        run: pipenv run check

      - name: Package vulnerabilities check
        run: pipenv check

      - name: Package Serverless
        run: npm run sls:package
