name: Check
on: pull_request

jobs:
  check:
    name: check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: Install dependencies
        run: |
          pip install --upgrade pip pipenv
          pipenv install --ignore-pipfile --dev
        env:
          PIPENV_NOSPIN: 1

      - name: Lint check
        run: pipenv run lint

      - name: Type check
        run: pipenv run check

      - name: Package vulnerabilities check
        run: pipenv check
