name: Deploy
on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}
  SLS_DEPLOYMENT_BUCKET: ${{ secrets.SLS_DEPLOYMENT_BUCKET }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install Npm
        run: npm install

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: Install Pipenv
        run: |
          pip install --upgrade pip pipenv
          pipenv install --ignore-pipfile
        env:
          PIPENV_NOSPIN: 1

      - name: Deploy
        run: npm run sls:deploy
